### PR TITLE
Add a difficulty sort

### PR DESCRIPTION
**Pull request by kodelebah**

### CODE REVIEW

**Comment by kodelebah** [comment]
@monizb can you help me to check this problem? When I click `Details`, I got errors of `aria-`. Even though my code is same with the code in material ui documentations.

**Comment by monizb** [comment]
> @monizb can you help me to check this problem? When I click `Details`, I got errors of `aria-`. Even though my code is same with the code in material ui documentations.

Which Details are you talking about?

**Comment by kodelebah** [comment]
image

**Comment by monizb** [comment]
@kodelebah no worries, that does happen sometimes, if you there is one small change here to be made, instead of calling it Difficulty level, can we rather say: "No. of PRs:" ?

**Comment by kodelebah** [comment]
> @kodelebah no worries, that does happen sometimes, there is one small change here to be made, instead of calling it Difficulty level, can we rather say: "No. of PRs:" ?

Okay, I will changed it later when I fix this issue #6.

**Comment by monizb** [comment]
@kodelebah Thank you soo much for this PR!! 🥳🥳

**Pull request merged**
