### PR TITLE
SW | 37 | feat(UI/UX): redesigns tags by color coding them

### PR DESCRIPTION
**Pull request by wsameer**
- Also associates tags by appropriate emoji
- The colors are chosen as per the theme of the overall app.
- A purple heart emoji is shown for new tags.

### screenshots
image

### CODE REVIEW

**Comment by wsameer** [comment]
@monizb please review and let me know if there are any changes needed.

**Comment by monizb** [comment]
Hi @wsameer thank you so much for the PR, it looks amazing! I should have added this in before, can we have an emoji for Caps 🧢 and Swag 🛍️ as well?

**Comment by wsameer** [comment]
> Hi @wsameer thank you so much for the PR, it looks amazing! I should have added this in before, can we have an emoji for Cap 🧢 and Swag 🛍️ as well?

Cap and Swag are the tags?

**Comment by monizb** [comment]
@wsameer thanks a lot, merging this!

**Pull request merged**
