### PR TITLE
added ClueLess Community to list

### PR DESCRIPTION
**Pull request by adarsh-chakraborty**
I've added ClueLess Community to the list, They have 5 Open Source Projects and also offering swags.

### CODE REVIEW

**Comment by adarsh-chakraborty** [comment]
For #152

**Comment by monizb** [comment]
Hi @adarsh-chakraborty , can you please add the link where this announcement was made?

**Comment by adarsh-chakraborty** [comment]
> Hi @adarsh-chakraborty , can you please add the link where this announcement was made?

I've created an Issue with the source, however I am also mentioning it here.

https://www.linkedin.com/posts/rajdeep-sengupta_javascript-github-python-activity-6981839349852082176-OCSf?utm_source=share&utm_medium=member_android

**Comment by monizb** [comment]
@adarsh-chakraborty thank you!

**Pull request merged**
