### PR TITLE
Add Deepsource swags

### PR DESCRIPTION
**Pull request by dev-bhavyam**

### CODE REVIEW

**Comment by monizb** [comment]
@dev-bhavyam looks like you have changed some other company's swag as well, please look into this

**Comment by dev-bhavyam** [comment]
Sorry @monizb let me fix this.

**Comment by monizb** [comment]
@dev-bhavyam looks like the Earthly swag link is still wrong, I see the Dev.to link in Earthly swags

**Comment by dev-bhavyam** [comment]
@monizb now I have fixed everything.

**Comment by monizb** [comment]
@dev-bhavyam thank you! :)

**Pull request merged**
